#!/bin/bash

yay -S --noconfirm neovim

mkdir $HOME/.config/nvim

ln -s $HOME/.dotfiles/nvim/init.vim $HOME/.config/nvim/init.vim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \  
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
