#!/bin/bash

yay -S --noconfirm neovim

mkdir -p $HOME/.config/nvim

touch $HOME/.config/nvim/init.vim || exit

ln -s $HOME/.dotfiles/nvim/init.vim $HOME/.config/nvim/init.vim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
