#!/bin/bash

sudo apt-get install docker docker-compose

sudo groupadd docker

sudo usermod -aG docker $USER

sudo systemctl enable docker

export DOCKER_BUILDKIT=1

docker build --platform=local -o . git://github.com/docker/buildx

mkdir -p ~/.docker/cli-plugins

mv buildx ~/.docker/cli-plugins/docker-buildx
