#!/bin/bash

#Installing Zsh
yay -S --noconfirm zsh
chsh -s $(which zsh)
ln -s -f $PWD/system/.zshrc $HOME/.zshrc

##Installing Kitty
yay -S --noconfirm kitty
mkdir $HOME/.config/kitty
ln -s -f $PWD/system/kitty.conf $HOME/.config/kitty/kitty.conf

##Installing Tmux
yay -S --noconfirm tmux
ln -s -f $PWD/system/tmux.conf $HOME/.tmux.conf

# Other system commands
yay -S --noconfirm exa
yay -S --noconfirm bat
yay -S --noconfirm htop
yay -S --noconfirm ctop

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

sh ~/.fzf/install
