#!/bin/bash

#Installing Zsh
yay -S --noconfirm zsh
chsh -s $(which zsh)
ln -s -f $HOME/.dotfiles/system/.zshrc $HOME/.zshrc

# Other system commands
yay -S --noconfirm exa
yay -S --noconfirm bat
yay -S --noconfirm htop

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

sh ~/.fzf/install
