#!/bin/bash

if [ "$DISTRIB" == "ManjaroLinux" ]; then
    $INSTALL npm
else
    $INSTALL nodejs npm
fi

sudo npm install -g yarn
sudo npm install -g eslint
sudo npm install -g eslint-plugin-react
sudo npm install -g stylelint
