#!/bin/bash

$INSTALL variety

ln -s -f $PWD/miscellaneous/variety.conf $HOME/.config/variety/variety.conf

if [ "$DISTRIB" == "ManjaroLinux" ]; then
    yay -S --noconfirm slack-desktop
    yay -S --noconfirm insomnia
    yay -S --noconfirm visual-studio-code-bin
else
    sudo snap install insomnia
fi
